import { LESSON_SCHEMA_VERSION } from "../schema.js";

// This is a schema fixture, not part of the Foundations curriculum.
export const LESSON_PLAYER_PREVIEW = {
  schemaVersion: LESSON_SCHEMA_VERSION,
  id: "lesson-player-preview",
  slug: "lesson-player-preview",
  version: 1,
  locale: "en",
  translations: [],
  title: "A short lesson-player preview",
  objective: "See how FemmeVoice breaks learning into small, optional, accessible steps.",
  metadata: {
    estimatedMinutes: 5,
    tags: ["engine-preview", "generic-learning"],
    status: "preview",
  },
  accessibility: {
    alternative: "Every activity is available without a microphone or recording.",
  },
  safety: {
    note: "This preview does not ask you to use your voice.",
    stopSignals: [],
    lowerIntensityAlternative: "You can read, skip, or pause at any point.",
  },
  evidence: [
    {
      id: "udl-multiple-means",
      label: "Multiple ways to engage and respond",
      level: "Educational design principle",
      citation: "Universal Design for Learning guidance",
      limitation: "This explains the format; it does not promise a specific learning outcome.",
    },
  ],
  blocks: [
    {
      id: "welcome",
      type: "rich_text",
      version: 1,
      metadata: { title: "Start small", label: "Arrive" },
      durationMinutes: 1,
      completion: { kind: "manual" },
      accessibility: {},
      safety: {},
      evidenceRefs: ["udl-multiple-means"],
      content: {
        nodes: [
          { type: "paragraph", children: [{ type: "text", value: "A lesson can offer a small experience before a long explanation. " }, { type: "strong", value: "You are always allowed to pause, skip, or choose a quieter route." }] },
        ],
      },
    },
    {
      id: "reflection",
      type: "reflection",
      version: 1,
      metadata: { title: "Choose what helps", label: "Reflect" },
      durationMinutes: 1,
      completion: { kind: "response", minLength: 3 },
      accessibility: {},
      safety: {},
      evidenceRefs: [],
      content: { prompt: "What would make a learning session feel easier to return to?" },
    },
    {
      id: "check-understanding",
      type: "quiz",
      version: 1,
      metadata: { title: "A gentle check", label: "Check" },
      durationMinutes: 1,
      completion: { kind: "quiz" },
      accessibility: {},
      safety: {},
      evidenceRefs: [],
      content: {
        prompt: "Which choice is always available in FemmeVoice lessons?",
        options: [
          { id: "a", label: "Pause, repeat, or use an easier route", correct: true },
          { id: "b", label: "Complete every activity perfectly", correct: false },
          { id: "c", label: "Record your voice to continue", correct: false },
        ],
        explanation: "Participation and reflection matter more than perfect performance. Recording stays optional.",
      },
    },
    {
      id: "why-format",
      type: "why_this",
      version: 1,
      metadata: { title: "Why this format?", label: "Evidence" },
      durationMinutes: 1,
      completion: { kind: "optional" },
      accessibility: {},
      safety: {},
      evidenceRefs: ["udl-multiple-means"],
      content: { prompt: "This panel makes the basis and limits of a learning choice visible." },
    },
    {
      id: "leave-well",
      type: "checkpoint",
      version: 1,
      metadata: { title: "Leave well", label: "Checkpoint" },
      durationMinutes: 1,
      completion: { kind: "manual" },
      accessibility: {},
      safety: {},
      evidenceRefs: [],
      content: { message: "You can leave here. FemmeVoice will remember this safe breakpoint on this device." },
    },
  ],
};
